### ISSUE TITLE
[Authentic Theme]: File editor in File Manager not displaying starting from v1.83.x

### ISSUE THREAD

**Issue by ibroheem** [webmin/webmin#479] opened 2017-01-12 04:43 UTC
Try editing editable files with edit option in the Right click menu using Authentic Theme. The editor loads but does not display. Even editing works, but editor doesn't display.
Editor works on other themes.
Editor worked on Authentic theme prior in webmin v1.82

**Comment by qooob** [comment] 2017-01-12 07:46
Hi,

I have checked it and I can't reproduce it. Have a look at [videoscreencast](https://rostovtsev.ru/pub/src/authentic/18.32/file_manager_working_editor_1832.webm).

1. What is you browser and its version
2. What is your server OS?
3. What is your Webmin version?

**Comment by ibroheem** [comment] 2017-01-12 15:44
Browser: Firefox (50, 51b10), Iceweasel 45, opera beta 42.0.2393.78
Server   : Debian 8, kernel 4.8.0
Webmin: 1.831.0 (Issue occured starting from v1.830.0)

Have a Look @ the <a href="https://transfer.sh/UPFgl/screencast-2017-01-12-14-11-39.mp4">Video Screencast<a/>

NOTE: It was working on version 1.82xxx, issue started when I upgraded.

**Comment by qooob** [comment] 2017-01-12 16:15
Hi,

It doesn't matter how I try, I can't reproduce it. Here it comes. I think this is one of that cache issue that happens sometimes. First, try `Incognito Mode`. Second restart Webmin from console `/etc/webmin/restart`, third, as last option try rebooting the server and as the last option, try rebooting the server.

You might want to use option 4 instead of 3, I bet, but if it's not super crucial for you, please use my order.

Rebort back please.

**Comment by ibroheem** [comment] 2017-01-12 16:21
Thanks, I haven't try Google Chrome though (Resource hog!).
Thats a production server, and has been up since the first stage, over thirty days now (without reboot).
I'll try ur solutions on my test server and give u feed back, I can reboot that one 100^100 times!

**Comment by ibroheem** [comment] 2017-01-12 17:22
Have u tried any of the above mentioned browsers?

**Comment by qooob** [comment] 2017-01-12 17:28
Yes, Firefox with _CentOS_ and _Debian_ worked as expected.

**Comment by qooob** [comment] 2017-01-12 17:29
Even made package update Webmin 1.821 to 1.831. All is fine.

**Comment by ibroheem** [comment] 2017-01-14 03:00
/help.cgi/authentic-theme/file-manager helped me.
Saw Ctrl+Esc, used it and.... It worked.
I minimized and Maximized it editor, that solved it.

Oh thats the fourth browser, Yandex Browser.

**Comment by qooob** [comment] 2017-01-14 06:08
Not sure what you mean? It doesn't work in Yandex Browser?

**Comment by qooob** [comment] 2017-01-14 06:11
How "help" could solve the issue?

**Comment by ibroheem** [comment] 2017-01-14 06:13
I'll link a video.

**Comment by ibroheem** [comment] 2017-01-14 06:44
This is the <a href="https://transfer.sh/dSmkt/screencast-2017-01-14-07-17-58.mp4">Video Cast</a>, Able to edit, unable to save file.

**Comment by qooob** [comment] 2017-01-14 07:26
@ibroheem I wish you told me that you're using it in separate tab, without left menu.

Jamie, please close this issue. I replicated it to my repo.

**Closed** 2017-01-14 07:39 UTC

**Comment by BillTech** [comment] 2017-05-11 10:46
im running into this problem with file manager if i choose more than 25 items shown webmin 1.840

**Comment by qooob** [comment] 2017-05-11 11:02
What do you mean?

Try hard reload browsers cache: `Ctrl+Shift+R`.

What browser are you using? Did you try incognito mode?

**Comment by BillTech** [comment] 2017-05-12 10:18
it works if i have view set to 25 items
but if i increase to a higher value i loose the dialog box to do anything
chrome

**Comment by qooob** [comment] 2017-05-12 10:20
You mean context menu is gone on the right click?

**Comment by BillTech** [comment] 2017-05-12 10:21
yes

**Comment by qooob** [comment] 2017-05-12 10:21
Yes, strange. I have it too. Will take a look. Thanks!

**Comment by BillTech** [comment] 2017-05-12 10:21
and hi

**Comment by BillTech** [comment] 2017-05-12 10:22
very good thanks

**Comment by qooob** [comment] 2017-05-13 07:33
Fixed: https://github.com/qooob/authentic-theme/commit/32e1ecbb6b935b94fb3ece0246358fe619af1e3a
