### ISSUE TITLE
Webmin Ver 1.980 File Manager brakes the system.

### ISSUE THREAD

**Issue by N3tFX** [webmin/webmin#1521] opened 2021-08-29 19:42 UTC
I can't verify 100% that this is really a webmin bug, but I've tried it three times and it broke the system every time.

I tried to make a clean install of the new Debian 11 (using the non-free firmware ISO),
 and after the installation was finished, I tried to make some changes with webmin.
 
 Please, **DO NOT TRY THE STEPS BELLOW ON YOUR MAIN SYSTEM !!!** 
 You could lose your files.
 
 Steps to reproduce:
 
 1) After Debian clean install, install webmin 1.980.
 2) Login to webmin.
 3) Navigate to: Tools > File Manager.
 4) Check the /opt folder and try to change permissions to the folder using to drop down menu from the top right.
 5) Applying the permissions brakes the system and it can't boot again.
 
I had to reinstall the system three times. And using it, without touching anything related with the webmin File Manager, the system is running fine.

**Comment by iliarostovtsev** [comment] 2021-08-29 20:29
Hi,

> Please, DO NOT TRY THE STEPS BELLOW ON YOUR MAIN SYSTEM !!!

I just tried it on my devel system and I could not reproduce it on my Debian 10.

> Check the /opt folder and try to change permissions to the folder using to drop down menu from the top right.

What really happens after permissions are applied? What permissions did you apply exactly? Could you provide the screenshot of the UI?

**Comment by iliarostovtsev** [comment] 2021-08-29 20:36
Besides, it is not clear what booting has to do with `/opt` directory.

**Comment by N3tFX** [comment] 2021-08-29 21:33
/opt was just an example. It's the process of changing the permissions that is causing the problem. When it happened and I tried to reboot, I got messages in the terminal about problems in ext4, the system tried to fix them but it always stuck in the middle of the process. I don't know what's happening, but I suspect from the messages, there is something that webmin does when it tries to interact with the filesystem; that ends up braking it. Also, it might not happen in Debian 10. Try Debian 11 and webmin version 1.980.

In my final installation, I changed the permissions using the terminal and everything is working fine.

**Comment by iliarostovtsev** [comment] 2021-08-29 21:44
It would be interesting to know how exactly reproduce the issue. I just installed Debian 11 and it worked as expected for me as well as on Debian 10.

What error message exactly did you get?

What permissions are you taking about -- _chmod_?

Have you tried rebooting recently?

**Comment by iliarostovtsev** [comment] 2021-08-29 21:47
Were you logged in as _root_ user or as _root_ capable user?

**Comment by N3tFX** [comment] 2021-08-29 21:57
> It would be interesting to know how exactly reproduce the issue. I just installed Debian 11 and it worked as expected for me as well as on Debian 10.

I've described in the first post the steps to reproduce it. I did it three times, and it happened every time. If you follow the steps above and it doesn't happen to your test system, then I don't know what else to add.
> What error message exactly did you get?

I can't recall exactly, but it said something about the ext4 journal that was corrupted, or something like that.
> What permissions are you taking about -- _chmod_?

I don't know what commands webmin executes in the background when using the File Manager. I used the web UI to change the permissions when the problem happened.
> Have you tried rebooting recently?

I have made a fourth clean install, didn't touch the webmin File Manager again, and it works fine.

**Comment by N3tFX** [comment] 2021-08-29 21:58
> Were you logged in as _root_ user or as _root_ capable user?

I used a normal user account with sudo.

**Comment by www3cc** [comment] 2021-09-01 05:58
@N3tFX 
Developer desktop recording... will explain in more detai

**Comment by www3cc** [comment] 2021-09-01 05:59
@N3tFX 
Use desktop screen recording...
For developers to watch
Will explain in more detail

**Comment by N3tFX** [comment] 2021-09-01 08:23
> @N3tFX
> Use desktop screen recording...
> For developers to watch
> Will explain in more detail

I don't know what good that will do, since when this bug happens, it brakes the system and doesn't boot again. How could I save the video?

I took some screenshots and enumerated the steps I made to cause the crash/brake:

1) Check the **/opt** folder.
2) Click **Tools > Change permissions**.

![webming-bug-1](https://user-images.githubusercontent.com/48089992/131636991-2c3c250c-9f15-4e5b-8db0-e2cc7752d981.jpg)


3) Check **Read** and **Write** permissions for **Group** and **Others**.
4) If you click **Change**, here is where the system brakes.

![webming-bug-2](https://user-images.githubusercontent.com/48089992/131637039-59b65295-aada-4591-9e22-01b8149999f5.jpg)


5) I don't know if the **Tree-view** that is still loading plays any role to this, but I though to mention it.

**Comment by iliarostovtsev** [comment] 2021-12-20 19:37
I am sorry but I cannot reproduce this issue neither on Debian 11 nor on any other distro. When/if you have more details please let us know.

I will close this issue for now.

**Closed by iliarostovtsev** 2021-12-20 19:37 UTC
