### ISSUE TITLE
With multiple package sources present, Webmin reports incorrect installed package version

### ISSUE THREAD

**Issue by EricdeWaal** [webmin/webmin#2261] opened 2024-08-26 12:36 UTC
For Gerbera (https://gerbera.io/) I have 3 package sources, see the output from 'apt-cache policy gerbera':
gerbera:
  Installed: 2.2.0-bookworm1
  Candidate: 2.2.0-bookworm1
  Version table:
     1:2.2.0-dmo0~bpo12+2 100
        100 https://www.deb-multimedia.org bookworm-backports/main amd64 Packages
     1:1.12.1-dmo2 500
        500 https://www.deb-multimedia.org bookworm/main amd64 Packages
 *** 2.2.0-bookworm1 1001
       1001 https://pkg.gerbera.io/debian bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
     1.1.0+dfsg-3.1+b1 500
        500 https://deb.debian.org/debian bookworm/main amd64 Packages

I have set the highest priority for the package from https://pkg.gerbera.io/debian bookworm/main amd64 with a file 
/etc/apt/sources.list.d/gerbera.list

This works and the installed version is 2.2.0-bookworm1. This can be confirmed with the above output and through the package itself.
But Webmin shows the original Debian info:
![afbeelding](https://github.com/user-attachments/assets/d64cf315-c760-4dbd-b354-8de76981dc92)

**Comment by jcameron** [comment] 2024-08-26 20:37
Do you perhaps have multiple versions installed? You can check by running `dpkg --list gerbera`

**Comment by EricdeWaal** [comment] 2024-08-26 21:28
Hi,

I just checken and the answer is no, Just version 2.2.0

Eric 

Op 26 aug 2024 22:37, om 22:37, Jamie Cameron ***@***.***> schreef:

**Comment by jcameron** [comment] 2024-08-26 23:15
What output do you get if you run `apt-cache show gerbera` ?

**Comment by EricdeWaal** [comment] 2024-08-27 06:04
I get:
 dpkg --list gerbera
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version         Architecture Description
+++-==============-===============-============-=================================
ii  gerbera        2.2.0-bookworm1 amd64        UPnP Media Server

**Comment by EricdeWaal** [comment] 2024-08-27 06:13
In my Putty terminal, there were no crossed out lines, no idea why that happens here

**Comment by EricdeWaal** [comment] 2024-08-27 10:06
I just noted that the Webmin url for the page shown in the first message is:
https://192.168.1.5:10000/software/edit_pack.cgi?package=gerbera&version=2%2E2%2E0%2Dbookworm1&xnavigation=1
So Webmin IS trying to display the information on version 2.2.0 bookworm1, but comes up with a different one. Hope that helps!

**Comment by jcameron** [comment] 2024-08-28 04:12
Ok I see the cause of this - it will be fixed in the next release.

**Closed by jcameron** 2024-08-28 04:12 UTC

**Comment by iliajie** [comment] 2024-08-28 10:17
@EricdeWaal You're welcome to apply the patch and see if it resolves the issue for you:

```
webmin patch https://github.com/webmin/webmin/commit/0939e55
```

**Comment by EricdeWaal** [comment] 2024-08-28 10:52
@iliajie I applied the patch, and now, if I try to list the package on Software Packages, it says:
![afbeelding](https://github.com/user-attachments/assets/cf272b1d-93e2-49e1-97bc-332b1dc5b3a4)

**Comment by EricdeWaal** [comment] 2024-08-28 11:02
So I undid the patch by reinstalling Webmin:
apt-get install --reinstall webmin

**Comment by iliajie** [comment] 2024-08-28 14:21
Oh, it seems the last patch wasn't complete. Alright, we'll wait for Jamie's comment on this.

**Comment by jcameron** [comment] 2024-08-29 01:01
A further fix is here : https://github.com/webmin/webmin/commit/cffabd972bfd9986bee71c3d01a5b61a2bb40472

**Comment by EricdeWaal** [comment] 2024-08-29 07:37
Sorry for my ignorance, but how can I install that?

**Comment by iliajie** [comment] 2024-08-29 09:02
> Sorry for my ignorance, but how can I install that? Tried: webmin patch [cffabd9](https://github.com/webmin/webmin/commit/cffabd9) but that failed:

```
webmin patch https://github.com/webmin/webmin/commit/cffabd9
```

**Comment by EricdeWaal** [comment] 2024-08-29 09:09
sorry, that's what I did. In above message I did not enter the command as code.
The editor here shows the command as: webmin patch https://github.com/webmin/webmin/commit/cffabd9

But it failed as shown above:
`webmin patch https://github.com/webmin/webmin/commit/0939e55
Patch applied successfully to:
  software/debian-lib.pl
root@nas:~# ^C
root@nas:~# apt-get install --reinstall webmin
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libfmt9 libjs-bootstrap4 libjs-popper.js libjs-sizzle libnpupnp9 libspdlog1.10 node-jquery
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/33.7 MB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 92708 files and directories currently installed.)
Preparing to unpack .../archives/webmin_2.202_all.deb ...
Unpacking webmin (2.202) over (2.202) ...
Setting up webmin (2.202) ...
root@nas:~#
root@nas:~#
root@nas:~# webmin patch https://github.com/webmin/webmin/commit/cffabd9
Patch failed: Hmm...  Looks like a unified diff to me...
The text leading up to this was:
--------------------------
|From cffabd972bfd9986bee71c3d01a5b61a2bb40472 Mon Sep 17 00:00:00 2001
|From: Jamie Cameron <jcameron@webmin.com>
|Date: Wed, 28 Aug 2024 18:00:36 -0700
|Subject: [PATCH] Fix version selector
|
|---
| software/debian-lib.pl | 2 +-
| 1 file changed, 1 insertion(+), 1 deletion(-)
|
|diff --git a/software/debian-lib.pl b/software/debian-lib.pl
|index 29d2acc7e7..730d682d98 100755
|--- a/software/debian-lib.pl
|+++ b/software/debian-lib.pl
--------------------------
patching file software/debian-lib.pl
Using Plan A...
Hunk #1 FAILED at 68.
1 out of 1 hunk FAILED -- saving rejects to file software/debian-lib.pl.rej
done
`

**Comment by iliajie** [comment] 2024-08-29 09:22
In this case, edit the file manually using `nano` or `vim`. You just need to replace `:` with `=` as shown in the patch.

**Comment by EricdeWaal** [comment] 2024-08-29 09:38
Yes, that did the trick! Now the right information is being displayed.
@jcameron , @iliajie Thanks a lot!
