### ISSUE TITLE
bind8 server overview with views random sorting

### ISSUE THREAD

**Issue by MarcHagen** [webmin/webmin#1455] opened 2021-03-07 19:04 UTC
At the moment i've 3 views setup for different subnets. Lets call them external, internal, private. 
In those views there are a number of domains.

When you load the dns server overview page (`:10000/bind8/?xnavigation=1`) with the options:
Categorize zones by view? Yes
The order in which the views are presented is different with every load of the page.

I would love to see this be a fixed sorting according to the named.conf, top > bottom. (external, internal, private)

**Comment by jcameron** [comment] 2021-03-08 03:16
Can you post a screenshot of that page on your system?

**Comment by MarcHagen** [comment] 2021-03-08 23:15
![image](https://user-images.githubusercontent.com/980978/110394329-8fa96a00-806c-11eb-99b8-630cc3c5f888.png)

**Comment by BenoitPoulet** [comment] 2021-04-14 07:20
Hello,
I can confirm this behavior, even with 2 views (my case).

**Comment by jcameron** [comment] 2021-04-15 03:53
Does this still happen if you switch to the Blue Framed Theme at Webmin -> Webmin Configuration -> Webmin Themes?

**Comment by BenoitPoulet** [comment] 2021-04-15 08:29
This theme is not available in the Debian Package

![image](https://user-images.githubusercontent.com/2464712/114838768-5388c800-9dd5-11eb-9b0c-be2914c1dbd2.png)

**Comment by iliarostovtsev** [comment] 2021-04-15 11:15
Gray Theme is alright too to run tests with.

**Comment by BenoitPoulet** [comment] 2021-04-15 13:41
Ok, i change to the Gray Framed Theme, and the behavior is the same :

View order of the views is random. 
Tested by clicking several time on "Servers > BIND DNS Server"

**Comment by iliarostovtsev** [comment] 2021-04-15 14:29
Most probably because the data stored as a hash (which are random).

How do you expect data to be sorted?

**Comment by jcameron** [comment] 2021-04-16 01:49
Thanks - I looked at the code for this, and realized that we're not sorting the views at all. This will be fixed in the next release.

**Closed by jcameron** 2021-04-16 01:49 UTC
