### ISSUE TITLE
Hamburger menu won't stay open on mobile iOS devices

### ISSUE THREAD

**Issue by jbyerline** [webmin/webmin#1870] opened 2023-03-23 20:19 UTC
See the video attached below.

This has been happening for at least the last 2 versions of Webmin. I am currently running version 2.020.

I try to adjust settings within webmin while away from a computer and I am unable to tap the menu's I need. As shown in the video, it doesn't seem to matter if it is Chrome or Safari for iPhone. 

https://user-images.githubusercontent.com/47374239/227342731-aecf7792-d82c-4653-b444-dd995c1d51fd.mov

**Comment by jcameron** [comment] 2023-03-23 21:34
@iliaross any ideas about this one?

**Comment by iliajie** [comment] 2023-03-23 21:53
Actually, not sure what that could be. I have just checked using my iPad with Chrome and Safari, and Android Phone with latest Chrome and it worked flawlessly in both mobile and desktop modes.

@jbyerline Jacob, which iOS version are you running there on your iPhone? I have just checked with iOS 15.7 and it worked just fine on my old iPad. There is an update of version 16. It's being installed .. but I doubt it would make any difference.

**Comment by jbyerline** [comment] 2023-03-23 21:54
I am currently running 16.3 on my iPhone

**Comment by iliajie** [comment] 2023-03-23 21:55
Mine is downloading 16.3.1 .. maybe you should also upgrade? Perhaps, one of the Apple's bugs?

https://support.apple.com/en-us/HT213635

**Comment by jbyerline** [comment] 2023-03-23 21:56
Will do and let you know.

**Comment by jbyerline** [comment] 2023-03-23 22:57
It is updated and still same thing is happening.

**Comment by iliajie** [comment] 2023-03-23 23:01
Does it happen on some other mobile device?

**Comment by jbyerline** [comment] 2023-03-23 23:03
I have a friend I just texted and same thing on his. He has an iPhone running same OS.

**Comment by iliajie** [comment] 2023-03-23 23:12
My iPad was just upgraded with 16.3.1 and it works just fine as before on 15.7.

Have you tried Firefox? I'm not really sure at the moment what could be the cause.

**Comment by iliajie** [comment] 2023-03-23 23:19
If the issue persists with Firefox on iOS, I'd suggest trying another platform, e.g. Android. If the issue still persists on another platform, I would suggest to SSH to the server and reinstall Webmin.

**Comment by jbyerline** [comment] 2023-03-23 23:20
Just tried firefox on the iPhone and I get the same thing. I have webmin through a reverse proxy. I tried on the servers ip as well and still no luck. The strange thing is it works fine on non-mobile devices.

**Comment by jbyerline** [comment] 2023-03-31 03:19
Just to add some more detail, I have 5 instances of webmin on different servers. It happens on all of them. My friend has 1 instance and it is happening for him as well.

**Comment by chris001** [comment] 2023-03-31 06:29
Same, on iOS latest version, system browser Safari.  Menu slides out, then immediately disappears closed.

**Comment by iliajie** [comment] 2023-03-31 09:48
> Same, on iOS latest version, system browser Safari. Menu slides out, then immediately disappears closed.

Thanks for jumping in, Chris. Does it also happen in Chrome?

**Comment by chris001** [comment] 2023-03-31 14:14
It happens on iOS on Edge (chromium). Brave, Firefox, and Chrome.

**Comment by iliajie** [comment] 2023-03-31 15:17
Are you running it in iOS emulator or on a real physical device?

**Comment by chris001** [comment] 2023-03-31 21:42
On a read physical device.

**Comment by chris001** [comment] 2023-03-31 21:49
It appears all the browsers on iOS use Apple WebKit engine and WebKit JS, this is why they all show this bug the same way.

**Comment by iliajie** [comment] 2023-03-31 22:32
Thank you all for reporting this. It was fixed on the latest commit. You can go to theme configuration page to install the latest development version of the theme to address this issue. If upgraded process would be blocked with the read pop-up, because of Usermin, simply disable Usermin updates on the same page.

**Comment by jbyerline** [comment] 2023-03-31 22:52
Just installed the dev theme and can confirm it works now. Thanks for the fix!

**Comment by iliajie** [comment] 2023-04-01 08:02
Thank you for your feedback! I will keep this issue opened for some time.

**Comment by chris001** [comment] 2023-04-01 14:24
Confirm working, thanks!

**Comment by iliajie** [comment] 2023-04-01 14:24
> Confirm working, thanks!

Alright. Thanks for the feedback.

**Comment by josemaeldon** [comment] 2023-05-21 19:34
Hello, the problem remains on ios 16.5. what could be causing this error?

**Comment by iliajie** [comment] 2023-05-21 19:38
Hello,

> Hello, the problem remains on ios 16.5. what could be causing this error?

You should use **Theme Configuration** page to update to the latest Authentic Theme, which fixes this issue.

**Comment by jbyerline** [comment] 2023-05-21 23:10
FYI automatic theme updates isn't enabled by default, I think it should be as I didn't know they were even separate from the webmin general package update. And Theme Configuration is a bit hidden to find.

**Comment by iliajie** [comment] 2023-05-22 10:19
> [jbyerline](https://github.com/jbyerline) commented (https://github.com/webmin/webmin/issues/1870#issuecomment-1556321683)
> Automatic theme updates isn't enabled by default

Yeah, we changed it about 2 years ago. We expect regular users to receive theme updates with Webmin package.

Theoretically, a better solution would be is to provide `webmin-authentic-theme` as a separate package, and make `webmin` package _recommend_ it, leaving off the main `webmin` package shipped without Authentic Theme. However, it would require a rework for our build process, and probably splitting Webmin itself into separate packages as well, where there'd be `perl(WebminCore)` package and `webmin-core` package with the main modules and English language only, and other, less popular modules and languages would be installed stand alone.

Even though there are pros for this approach, there are also cons, and I don't think we're doing it anytime soon, as there are a lot more practical issues to solve at the moment.

**Closed by iliajie** 2023-05-22 10:19 UTC

**Comment by iliajie** [comment] 2023-05-22 19:18
I'm very glad you could figure this out!
