### ISSUE TITLE
netplan botches routes section on update

### ISSUE THREAD

**Issue by swelljoe** [webmin/webmin#1291] opened 2020-08-31 15:24 UTC
See comparison of config before and after here: https://forum.virtualmin.com/t/dedicated-server-not-accessible-after-installing-virtualmin/107303/4

Leaves out on-link option.

**Comment by jcameron** [comment] 2020-09-04 18:41
Looks like the problem is this block :  

```
        - on-link: true
          to: 0.0.0.0/0
          via: 136.243.133.25
```

Specifically, the on-link continuation line.

**Comment by jcameron** [comment] 2020-09-04 19:36
Ok I checked in a fix for this, for inclusion in the next release.

**Closed by jcameron** 2020-09-04 19:36 UTC
