### ISSUE TITLE
PPTP client module: 500 Internal server error

### ISSUE THREAD

**Issue by viktike** [webmin/webmin#843] opened 2018-03-05 08:39 UTC
With the latest RPM package _(1.880)_, on CentOS 6 32bit I got **500 Internal Server Error** on PPTP VPN client index page:

```
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.880 Date: Mon, 5 Mar 2018 08:38:21 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Not a HASH reference at /usr/libexec/webmin/pptp-client/index.cgi line 68.
```

**Comment by qooob** [comment] 2018-03-05 08:43
It's worth noting, that it doesn't happen on 64bit CentOS 7.

**Comment by viktike** [comment] 2018-03-05 08:52
Maybe it's related to language settings. I have _Hungarian (HU.UTF-8)_ set.

**Comment by qooob** [comment] 2018-03-05 08:54
It doesn't seem to change anything, switched to _Hungarian_ and it just worked the same way.

Jamie will take a closer look when he wakes up.

**Comment by viktike** [comment] 2018-03-05 08:57
Perl version:
```
[root@server ~]# yum list perl
perl.i686                                                                                                    4:5.10.1-144.el6                                                                                                    @base
[root@server ~]#
```

**Comment by gnadelwartz** [comment] 2018-03-05 10:53
It's strange if it's really line 68, there is only a

`print "... $text{'something'}` statement, which is used all over in Webmin.

May be a file is corrupted. Try to run `./update-from-repo.sh -force` from webmin dir to reload all files and config from github again.

**Comment by viktike** [comment] 2018-03-05 11:35
Problem still persistent after:

```
Search for  configuration ... found: /etc/webmin/miniserv.conf
Warning: update from non release repository https://github.com/webmin/webmin may break your installation!
Would you like to update Webmin from https://github.com/webmin/webmin [y/N] y
Pulling in latest changes for Webmin  (https://github.com/webmin/webmin) ...

Start update for Webmin 1.88003050234......................................................................................................................................

Insert perl path /usr/bin/perl ...
***********************************************************************
*            Welcome to the Webmin setup script, version 1.88003050234        *
***********************************************************************
Webmin is a web-based interface that allows Unix-like operating
systems and common Unix services to be easily administered.
Installing Webmin from /usr/libexec/webmin/.~files/webadmin/tarballs/webmin-1.88003050234 to /usr/libexec/webmin ...
***********************************************************************
Webmin uses separate directories for configuration files and log files.
Unless you want to run multiple versions of Webmin at the same time
you can just accept the defaults.
Config file directory [/etc/webmin]: Found existing Webmin configuration in /etc/webmin
Copying files to /usr/libexec/webmin ..
Creating start and stop scripts..
Updating config files..
Changing ownership and permissions ..
Running postinstall scripts ..
Attempting to start Webmin mini web server..
Starting Webmin server in /usr/libexec/webmin
***********************************************************************
Webmin has been installed and started successfully. Use your web
browser to go to
  https://server:10000/
and login with the name and password you entered previously.
Because Webmin uses SSL for encryption only, the certificate
it uses is not signed by one of the recognized CAs such as
Verisign. When you first connect to the Webmin server, your
browser will ask you if you want to accept the certificate
presented, as it does not recognize the CA. Say yes.

Compile UTF-8 lang files .............................
Would you like to update Authentic Theme for Webmin? [y/N]
Operation aborted.

Clean up temporary files ...
Make scripts executable ...

Updating Webmin  to Version 1.88003050234, done.
[root@server webmin]# service webmin restart
Stopping Webmin server in /usr/libexec/webmin
Starting Webmin server in /usr/libexec/webmin
```
Error is still:
```
HTTP/1.0 500 Perl execution failed Server: MiniServ/1.88003050234 Date: Mon, 5 Mar 2018 11:34:05 GMT Content-type: text/html; Charset=iso-8859-1 Connection: close
Error - Perl execution failed
Not a HASH reference at /usr/libexec/webmin/pptp-client/index.cgi line 68.
```

**Comment by jcameron** [comment] 2018-03-06 05:51
What's on line 68 of /usr/libexec/webmin/pptp-client/index.cgi on your system?

**Comment by viktike** [comment] 2018-03-06 06:27
```
                print &ui_buttons_row("conn.cgi",
                        $text{'index_conn'},
                        $text{'index_conndesc'},
                        undef,
                        &ui_select("tunnel", $config{'tunnel'},
                                [ map { $_->{'name'} } @notconns ])." ".
                            $text{'index_pass'}." ".
                            &ui_password("cpass", undef, 10));
                }

        if (@conns) {
                # If any tunnels appear to be active, show disconnect button
68:                 print &ui_buttons_row("disc.cgi",
                        $text{'index_disc'},
                        $text{'index_discdesc'},
                        undef,
                        &ui_select("tunnel", $config{'tunnel'},
                                [ map { $_->{'name'} } @conns ]));
                }

        # Show at-boot button
        if (&foreign_check("init") && @tunnels) {
                &foreign_require("init");
```

**Comment by viktike** [comment] 2018-03-06 21:33
I was able to fix this manually. Here is how it's working now:

```
        @conns = grep { $tunnels{$_->[0]} } &list_connected();
        %conns = map { @$_ } @conns;
        @notconns = grep { !$conns{$_->{'name'}} } @tunnels;
        %conns = map { @$_ } @conns;
        @yesconns = grep { $conns{$_->{'name'}} } @tunnels;
        if (@notconns) {
                # Show connect button, if any are disconnected
                print &ui_buttons_row("conn.cgi",
                        $text{'index_conn'},
                        $text{'index_conndesc'},
                        undef,
                        &ui_select("tunnel", $config{'tunnel'},
                                [ map { $_->{'name'} } @notconns ])." ".
                            $text{'index_pass'}." ".
                            &ui_password("cpass", undef, 10));
                }

        if (@yesconns) {
                # If any tunnels appear to be active, show disconnect button
                print &ui_buttons_row("disc.cgi",
                        $text{'index_disc'},
                        $text{'index_discdesc'},
                        undef,
                        &ui_select("tunnel", $config{'tunnel'},
                                [ map { $_->{'name'} } @yesconns ]));
                }
```

**Comment by jcameron** [comment] 2018-03-06 23:24
Ok, I see the cause of this - and I've checked in a fix for inclusion in the next release.

**Closed by jcameron** 2018-03-06 23:24 UTC

**Comment by gnadelwartz** [comment] 2018-03-07 06:31
you can fun `update-from-repo.sh -file pptp-client/index.cgi `to get Jamie's patch
