### ISSUE TITLE
System Information - Package Update not refreshing after applied

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#282] opened 2016-02-23 09:51 UTC
The package updates notice is not dismissed right away from System Notification page after upgrade. It took about 2-5 minutes to completely disappear. 

Is there a way to make it displayed properly after upgrade? That would me more sense.

The other issue with completely stuck Update Notifications on System Information Page: https://github.com/qooob/authentic-theme/issues/406

**Comment by jcameron** [comment] 2016-02-24 03:30
When you upgrade a package, the cached list of packages should get updated.

Did you do the upgrade from the command line, or using the Software Package Updates module?

**Comment by qooob** [comment] 2016-02-24 06:31
No, of course using module.

**Comment by qooob** [comment] 2016-02-24 08:16
I just did another update and it seems that it's clearing things after first package was installed but not the last.

So I had 5 packages. I click on it using System Information page. Then click Update packages. Then when it's done installing packages one by one I get back to System Information page and see 2 notification about 2 new packages. When I go there the list is empty. Those 2 packages update notice goes away in 5 minutes or so.

**Comment by jcameron** [comment] 2016-02-25 05:17
Do you happen to recall what the 5 packages were? I'm interested to know if they were related in any way, which could have caused some to be installed before Webmin specifically requested them, as dependencies.

**Comment by qooob** [comment] 2016-02-25 06:45
Jamie, here:

```
   167 | -y update python3-pypars | 2016-02-24 11:12 | Update         |    1   
   166 | -y update pyparsing      | 2016-02-24 11:12 | I, U           |    2   
   165 | -y update policycoreutil | 2016-02-24 11:11 | Update         |    3   

```

Jamie, it's irrelevant. I think what should be done is cleared `$info->{'poss'}` gotten from `&system_status::get_collected_info()`; This is the reason why it appears.

**Comment by jcameron** [comment] 2016-02-26 03:37
That already happens though, here : https://github.com/webmin/webmin/blob/master/package-updates/update.cgi#L108

**Comment by qooob** [comment] 2016-02-27 13:45
May be. Jamie, I just did another update. It was 27 updates before I ran Package Updates. Afterwards it happened to be 10. However all of them are installed (that's for sure). You can see it by going in to the module and by running `dnf update` in console. It happens in any theme, including default.

Jamie, this should be taken care of. It's really happening.

**Comment by qooob** [comment] 2016-02-27 13:46
Probably the line of code you mentioned is running to early, this is what it feels like to me.

**Comment by jcameron** [comment] 2016-02-27 18:55
Is this on a debian or redhat system? And if it is debian, do you have the `apt-show-versions` command installed?

**Comment by qooob** [comment] 2016-02-27 19:13
This is Fedora (RHEL)

**Comment by jcameron** [comment] 2016-02-27 23:02
Ok, I just checked in a change that should fix this (by clearing all the caches)

**Comment by qooob** [comment] 2016-02-28 17:56
Jamie, unfortunately changing `&package_updates::list_possible_updates(2);` to `&package_updates::list_possible_updates(1);` didn't change anything. I restarted Webmin after editing `system-status-lib.pl`.

I just installed new series of updates and situation remain the same.

**Comment by jcameron** [comment] 2016-02-28 17:59
Is this on a system with Virtualmin also installed?

**Comment by qooob** [comment] 2016-02-28 18:00
No, just Webmin.

**Comment by jcameron** [comment] 2016-03-01 06:20
Funny, I can't re-produce this myself.

When you are doing these updates, are you applying all available updates - or just a subset?

**Comment by qooob** [comment] 2016-03-01 06:33
I apply all updates. What happens that initial number after update drops down but not completely. It's happened on Fedora, Debian and as far as i remember on CentOS 6

**Comment by Zen4All** [comment] 2016-03-01 06:42
I have the same problem. My servers use Ubuntu 14.04, and used install.sh for virtualmin.

**Comment by qooob** [comment] 2016-03-01 08:34
At the moment I had 2 updates. Installed them. All seems correct. It's gone. I believe it happens when there are many-many updates (like 25-30).

**Comment by Zen4All** [comment] 2016-03-01 09:15
No, it also happen with less. Like 5 or 10

**Comment by qooob** [comment] 2016-03-01 09:20
Well, then I either got lucky or patched file started to work.

**Comment by qooob** [comment] 2016-03-16 06:04
1.791 has the same issue. I had 2 regular packages and 2 security type packages. After updates was done, 2 security packages are gone but it still shows 2 regular type packages. 

Please fix it.

**Comment by qooob** [comment] 2016-03-23 07:01
Just did another update. `There were 4 package updates are available, of which 2 are security updates`. After I applied updates and returned back on the SI page I saw the message: `2 package updates are available` - so things are cleared but not fully.

**Comment by qooob** [comment] 2016-03-23 07:03
The packages that were updated:

`xfsprogs, nmap, krb5-libs, mlocate, nfs-utils`

**Comment by jcameron** [comment] 2016-04-26 02:15
Can you post the full output you got when installing those packages? The cause is probably that Webmijn isn't parsing it properly to find the list of updates.

**Comment by qooob** [comment] 2016-04-26 06:12
Alright, I will next time.

**Comment by qooob** [comment] 2016-04-27 07:01
Hi, Jamie!

This time notifications were cleared immediately. But there were no security packages. Ok.

The other problem remained - Installed in reality 26 packages but after installation there was a message - `No packages installed - check the messages above...`

Take a look at the screenshots:

![screenshot from 2016-04-27 09-53-07](https://cloud.githubusercontent.com/assets/4426533/14844268/50ff9d20-0c67-11e6-8bd3-9d9f23d56a37.png)
![screenshot from 2016-04-27 09-53-16](https://cloud.githubusercontent.com/assets/4426533/14844269/5100067a-0c67-11e6-9637-962a28a17435.png)
![screenshot from 2016-04-27 09-54-01](https://cloud.githubusercontent.com/assets/4426533/14844270/51009f40-0c67-11e6-918a-823e9871bb96.png)

**Comment by jcameron** [comment] 2016-04-28 05:32
I've checked in a fix (see above) that should fix this.

**Comment by DavidBruchmann** [comment] 2016-09-30 09:39
latest webmin version, ubuntu 16.04, still same behavior.
Message about 6 ghost updates on the "System Information"-page

**Comment by DavidBruchmann** [comment] 2016-09-30 09:47
found this related page: https://sourceforge.net/p/webadmin/bugs/4100/?page=1

**Comment by jcameron** [comment] 2016-09-30 21:02
Do the ghost updates go away if you click Refresh System Information?

**Comment by DavidBruchmann** [comment] 2016-10-01 03:56
No, I tried it..
Like mentioned in the linked thread, the hints on the "System Information" are created never separating upgrades and updates while on the page "Software Package Updates" its only searched for updates. This difference seems being responsible for the fault.

# apt-show-versions | grep upgradeable
libpam-systemd:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
libsystemd0:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
libudev1:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
systemd:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
systemd-sysv:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
udev:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10

question is not only now how to get rid of the difference in behavior in the two places but also if there should be offered perhaps updates and upgrades separated.

**Comment by jcameron** [comment] 2016-10-01 17:37
Ok, I think the issue here is that Webmin isn't properly comparing the versions `229-4ubuntu8` and `229-4ubuntu10` .  This will be fixed in the next release.

**Comment by DavidBruchmann** [comment] 2016-10-01 20:11
Its output on commandline and it says 
xxx 229-4ubuntu8 upgradeable to 229-4ubuntu10
which means the version of these modules are from upgradeable to 229-4ubuntu10
I'm never a linux guru but I get the impression you understood it wrong.
Webmin is not involved in the output I posted.
I posted it to show what webmin is showing as summary on the system-page but not on the update page.

**Comment by jcameron** [comment] 2016-10-01 21:04
The problem is that in some cases Webmin uses apt-show-versions to detect upgrades, and in other cases it does it's own version comparison. However, the latter was being done incorrectly.

**Comment by DavidBruchmann** [comment] 2016-10-02 04:23
thanks for the explanation.
I applied the patch and still remark the issue.

**Comment by jcameron** [comment] 2016-10-02 04:33
Even after refreshing available packages (or waiting a couple of hours for an automatic refresh) ?

**Comment by DavidBruchmann** [comment] 2016-10-02 04:51
I refreshed but don't see messages.
I never waited several hours yet but can check later again.
As it seems that apt is dependency of webmin it could be solved with apt-show-versions | grep upgradeable perhaps, replacing the internal method.

**Comment by DavidBruchmann** [comment] 2016-10-02 09:55
After ~5 hours still the same:
System overview: 
`6 package updates are available`
Refreshing Packages: 
```
Clearing package caches ..
.. done
Re-fetching available packages ..
.. found 6 possible updates
```
Software Package Updates:
`No packages available to be updated were found.`

**Comment by DavidBruchmann** [comment] 2016-10-02 10:06
In the table installed the packages are shown like this, so there is no mention about upgrade-ability:
```
libpam-systemd	amd64 system and service manager - PAM module	Running latest 229-4ubuntu8	Ubuntu
libsystemd0	amd64 systemd utility library	Running latest 229-4ubuntu8	Ubuntu
libudev1	amd64 libudev shared library	Running latest 229-4ubuntu8	Ubuntu
systemd	amd64 system and service manager	Running latest 229-4ubuntu8	Ubuntu
systemd-sysv	amd64 system and service manager - SysV links	Running latest 229-4ubuntu8	Ubuntu
udev	amd64 /dev/ and hotplug management daemon	Running latest 229-4ubuntu8	Ubuntu
```

**Comment by jcameron** [comment] 2016-10-02 18:33
Damn, looks like my initial fix missed a case. Try also applying this patch : https://github.com/webmin/webmin/commit/7ff9e6501a50a51f5e9ebe1d5e29c47c16bce424

**Comment by DavidBruchmann** [comment] 2016-10-04 08:14
After applying the patch I see now 6 packages upgradable on the "Software Package Updates", that's the same like I see with `apt-show-versions | grep upgradeable`.
Nevertheless on the page "System information" is shown 
> 7 package updates are available

**Comment by jcameron** [comment] 2016-10-04 23:23
So does this 6/7 package mismatch stick around even after you wait a while or refresh the system information page?

**Comment by DavidBruchmann** [comment] 2016-10-05 06:42
Yes it changed now to 11/12 mismatch but it's still a mismatch.

**Comment by jcameron** [comment] 2016-10-05 23:49
Can you tell what the one missing package is?

**Comment by DavidBruchmann** [comment] 2016-10-06 00:38
The missing package is php-gettext:
>:~# apt search php-gettext
php-gettext/xenial 1.0.11-2+deb.sury.org~xenial+1 all [upgradable from: 1.0.11-2build1]
  read gettext MO files directly, without requiring anything other than PHP

I installed deb http://ppa.launchpad.net/ondrej/php/ubuntu xenial main
and don't know if it's related.

Still all the packages with different commands:

>:~# apt list --upgradable
Listing... Done
klibc-utils/xenial-updates 2.0.4-8ubuntu1.16.04.2 amd64 [upgradable from: 2.0.4-8ubuntu1.16.04.1]
libklibc/xenial-updates 2.0.4-8ubuntu1.16.04.2 amd64 [upgradable from: 2.0.4-8ubuntu1.16.04.1]
libpam-systemd/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]
libsystemd0/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]
libudev1/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]
ntp/xenial-updates,xenial-security 1:4.2.8p4+dfsg-3ubuntu5.3 amd64 [upgradable from: 1:4.2.8p4+dfsg-3ubuntu5.1]
ntp-doc/xenial-updates,xenial-security 1:4.2.8p4+dfsg-3ubuntu5.3 all [upgradable from: 1:4.2.8p4+dfsg-3ubuntu5.1]
ntpdate/xenial-updates,xenial-security 1:4.2.8p4+dfsg-3ubuntu5.3 amd64 [upgradable from: 1:4.2.8p4+dfsg-3ubuntu5.1]
php-gettext/xenial 1.0.11-2+deb.sury.org~xenial+1 all [upgradable from: 1.0.11-2build1]
systemd/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]
systemd-sysv/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]
udev/xenial-updates,xenial-security 229-4ubuntu10 amd64 [upgradable from: 229-4ubuntu8]


>:~# apt-show-versions | grep upgradeable
klibc-utils:amd64/xenial-updates 2.0.4-8ubuntu1.16.04.1 upgradeable to 2.0.4-8ubuntu1.16.04.2
libklibc:amd64/xenial-updates 2.0.4-8ubuntu1.16.04.1 upgradeable to 2.0.4-8ubuntu1.16.04.2
libpam-systemd:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
libsystemd0:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
libudev1:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
ntp:amd64/xenial-security 1:4.2.8p4+dfsg-3ubuntu5.1 upgradeable to 1:4.2.8p4+dfsg-3ubuntu5.3
ntp-doc:all/xenial-security 1:4.2.8p4+dfsg-3ubuntu5.1 upgradeable to 1:4.2.8p4+dfsg-3ubuntu5.3
ntpdate:amd64/xenial-security 1:4.2.8p4+dfsg-3ubuntu5.1 upgradeable to 1:4.2.8p4+dfsg-3ubuntu5.3
php-gettext:all/xenial 1.0.11-2build1 upgradeable to 1.0.11-2+deb.sury.org~xenial+1
systemd:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
systemd-sysv:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10
udev:amd64/xenial-security 229-4ubuntu8 upgradeable to 229-4ubuntu10

**Comment by jcameron** [comment] 2016-10-07 04:16
Oh my god .. the version number is "1.0.11-2+deb.sury.org~xenial+1" !

For now, I'd recommend just upgrading that manually from the command line.

**Comment by DavidBruchmann** [comment] 2016-10-25 18:49
Thanks, yes I made it now all by commandline.
Saw you published a new version but never had a look yet if it was about
this issue.

**Closed** 2017-03-06 18:15 UTC
