### ISSUE TITLE
[Filemin] Issue with "Restore previously used tabs on initial load"

### ISSUE THREAD

**Issue by Mecha-Weasel** [webmin/webmin#1958] opened 2023-07-18 15:27 UTC
Even though I go into the options for File Manager module, and set the option for "Restore previously used tabs on initial load" to NO, it's doing that anyway (i.e. close File Manager and re-open, and the previous tab(s) are there).

Webmin version: 2.021
Authentic theme version: 20.30-RC1-58
OS: Debian 11

**Comment by iliajie** [comment] 2023-07-18 16:56
Hello,

Oddly I cannot reproduce this issue. If I set that option to _No_, the tabs aren't getting opened.

Try clicking **Clear cache** link in right side slider (under cog button) and see if that help?

**Comment by Mecha-Weasel** [comment] 2023-07-19 22:54
Sorry, not understanding where that clear cache function is?

**Comment by iliajie** [comment] 2023-07-19 23:03
> Sorry, not understanding where that clear cache function is? do you mean the browser's cache? or something else?

<img width="981" alt="image" src="https://github.com/webmin/webmin/assets/4426533/f4a91517-aeb7-422e-a01c-cba919b4baf1">

**Comment by Mecha-Weasel** [comment] 2023-07-19 23:12
ok found that and tried it. still getting the issue.

![image](https://github.com/webmin/webmin/assets/3591043/381715cf-b4df-4b12-b93e-15380ed5ceec)

**Comment by Mecha-Weasel** [comment] 2023-07-19 23:16
PS: Also, a lot of the time (but not all of the time) I use file-manager launched in another tab or window.  Not sure if that is a contributing factor in some weird way.  I believe I had to set **referers_none=0** in **/etc/webmin/config** for that to work.

**Comment by iliajie** [comment] 2023-07-19 23:30
> Also, a lot of the time (but not all of the time) I use file-manager launched in another tab or window. Not sure if that is a contributing factor in some weird way. I believe I had to set **referers_none=0** in **/etc/webmin/config** for that to work.

You shouldn't need that, as referer is set when link is opened via `Ctrl + Right-click`.



> ok found that and tried it. still getting the issue.

If you open browser's console and run:

```
config_portable_module_filemanager_remember_tabs
```

.. what output do you get?

**Comment by Mecha-Weasel** [comment] 2023-07-20 00:00
config_portable_module_filemanager_remember_tabs
true

**Comment by Mecha-Weasel** [comment] 2023-07-21 21:20
> config_portable_module_filemanager_remember_tabs = false;
> theme.config.save();

That seems to have done the trick!

**Comment by Mecha-Weasel** [comment] 2023-07-21 21:22
PS: Not sure if its related, but I am having similar issues with other File-Manager settings, like how many items to display before paginating.  Is that maybe a similar issue?

**Comment by iliajie** [comment] 2023-07-21 21:24
Try latest nightly Webmin build and see if you're still having this issue?

**Comment by Mecha-Weasel** [comment] 2023-07-21 21:34
Pulled nightly build (shows now as v2.099), still have the same issue with these two options being ignored:

- Default number of items per page

- Maximum number of items in directory without using server pagination

**Comment by iliajie** [comment] 2023-07-21 21:36
Try incognito tab in a different browser. Perhaps, some extensions is messing around with Webmin UI.

**Comment by Mecha-Weasel** [comment] 2023-07-21 21:46
Ok, just tried that, no change:

![image](https://github.com/webmin/webmin/assets/3591043/bcfcc91c-02f2-45a7-a63b-bf0ddd179ff1)

**Comment by iliajie** [comment] 2023-07-21 21:47
I don't understand the problem.

**Comment by iliajie** [comment] 2023-07-21 23:15
> * Maximum number of items in directory without using server pagination

Oh, okay, thanks! I got it. Fixed on the latest nightly build. Give it a try now please!

**Comment by Mecha-Weasel** [comment] 2023-07-22 01:36
> > * Maximum number of items in directory without using server pagination
> 
> Oh, okay, thanks! I got it. Fixed on the latest nightly build. Give it a try now please!

Thanks! will check it out.

**Comment by Mecha-Weasel** [comment] 2023-07-22 01:41
> > * Maximum number of items in directory without using server pagination
> 
> Oh, okay, thanks! I got it. Fixed on the latest nightly build. Give it a try now please!

Hmmmm just installed the latest daily build again, and same issue. Still paginating at 19 items.  Maybe that fix is not baked-in yet?

**Comment by iliajie** [comment] 2023-07-22 01:42
What is wrong with paginating at 19? How does File Manager config page look like?

**Comment by Mecha-Weasel** [comment] 2023-07-22 01:45
Maybe I'm mis-interpreting these items?

![image](https://github.com/webmin/webmin/assets/3591043/7084b4f3-ba41-4ab6-b00a-c8435a5d9886)

Shouldn't I be able to see several-hundred files in the list, before it paginates?

**Comment by iliajie** [comment] 2023-07-22 01:48
There is **Automatic** checkbox is missing in your case!

<img width="1411" alt="image" src="https://github.com/webmin/webmin/assets/4426533/c48b186c-1356-426d-9393-b1eea2e882a9">

I don't know what happed to it in your case.

Try running:

```
config_portable_module_filemanager_auto_per_page = false;
theme.config.save();
```

**Comment by Mecha-Weasel** [comment] 2023-07-22 03:01
That seems to have done it.  Did see some more errors in the console btw, not sure if they are related to anything ...

![image](https://github.com/webmin/webmin/assets/3591043/57e79c59-670e-4e75-b646-3bf42f34817b)

**Comment by Mecha-Weasel** [comment] 2023-07-22 03:27
Thanks for looking into it.

**Comment by iliajie** [comment] 2023-07-22 10:43
> That seems to have done it.

Great!

**Closed by iliajie** 2023-07-22 10:43 UTC
