### ISSUE TITLE
BIND DNS server trailing dots

### ISSUE THREAD

**Issue by navennn** [webmin/webmin#639] opened 2017-09-27 17:07 UTC
Hi,
In previous versions there always used to be a trailing dot at the end of the DNS records. Right now, in the newest version that dot is gone. Is there a way to reenable this? Is this a bug or a feature?

abc.test.test**.**	IN	A	3.2.2.2	;x

![abc_test](https://user-images.githubusercontent.com/26810830/30926945-160f23f0-a3b7-11e7-9399-b9b418628c0b.png)

**Comment by jcameron** [comment] 2017-09-27 22:50
In the zone file, a dot at the end is needed for absolute records. However, it doesn't appear in the UI because it's confusing for users.

**Comment by navennn** [comment] 2017-09-28 08:32
Well. In older versions it did appear. So now it is more confusing for users when in one version it does and in another it doesn't appear.

**Comment by jcameron** [comment] 2017-09-30 05:10
Can you post a screenshot of the entire page you're referring to?

**Comment by navennn** [comment] 2017-09-30 12:09
Servers -> BIND DNS Server -> Double-click zone -> Address records (or cname or anything...)

![bind-new-webmin](https://user-images.githubusercontent.com/26810830/31045655-dbbab834-a5e8-11e7-938c-48c976ac6bba.png)

**Comment by jcameron** [comment] 2017-10-01 17:59
You're right ... it actually looks like the Authentic theme is doing this.

@iliaross - is the theme changing the appearance of this page?

**Comment by qooob** [comment] 2017-10-01 18:31
It true, I could reproduce it. Maybe it's unintentional leak from some parts of the code. I remember I made a feature for splitting lines on `Setup DNSSEC Key` for `DS record for parent zone :`. I will take a look and patch it and some other bugs in 19.01 release.

**Comment by qooob** [comment] 2017-10-16 18:40
This issue is going to be fixed in 19.01 release tomorrow.

**Comment by qooob** [comment] 2017-10-16 18:41
Thanks for reporting and helping us make the better products.

**Comment by navennn** [comment] 2017-10-17 15:23
Thank you for great support and great software.

**Comment by qooob** [comment] 2017-10-17 15:42
Thank you for your kind words.

**Closed** 2019-06-13 08:18 UTC
