### ISSUE TITLE
new filemanager

### ISSUE THREAD

**Issue by Fisico** [webmin/webmin#15] opened 2011-06-01 10:40 UTC
make a new filemanager with:

• multiupload
• drag & drop

**Comment by LeeLorenzSr** [comment] 2015-05-01 17:23
Well, with Chrome and possibly other browsers deprecating support for Java, perhaps it is time for WebMin to get a new FileManager that isn't dependent on Java?

Short-term solution for users is to enable this flag in Chrome:
chrome://flags/#enable-npapi

Of course, Chrome developers will probably soon remove even that, because reasons...

**Comment by swelljoe** [comment] 2015-05-07 05:05
The replacement would obviously have to be HTML5/JavaScript. But, I don't know that we have the in-house capabilities to do it ourselves; Jamie and I are not yet particularly strong on HTML5 and JavaScript (though we're both learning). We're considering our options in terms of existing file manager implementations that could be integrated into Webmin, but, as far as I know, there isn't anything quite comparable in capability to the current Java file manager that Jamie built so many years ago.

**Comment by LeeLorenzSr** [comment] 2015-05-07 12:26
I wish I had time to put into building a new file manager, though I haven't done much with Linux (I'm an enterprise developer in a primarily Microsoft supplied company). I might have more time this summer to at least look at it and give some productive input.

**Comment by swelljoe** [comment] 2015-05-09 02:40
Interestingly, while we were having this conversation here, someone was actually making something great happen on this problem. 

https://github.com/Real-Gecko/filemin

He's only been working on it for a very short time, but already it has *most* of the functionality that people really rely on File Manager for. It does have a couple of bugs/quirks, but is evolving really (surprisingly and impressively) fast. It does require the latest Authentic Theme to be awesome, but you're probably already using Authentic Theme, if you're paying enough attention to be discussing this stuff with us on the github issue tracker.

Anyway, I think a good path forward on this problem now is to do whatever we can do encourage development on this new project. We plan to offer him free licenses of Virtualmin Pro and Cloudmin Pro (as a "Thanks!") and me or Jamie will spend some time auditing the code for security and reasonable use of the Webmin APIs. He doesn't have a donate link for this projects, but I'll suggest he put one up, so we can send him a few bucks.

He has a wbm package in the install directory (download it using the "Raw" mode), so I'd suggest everyone in this thread give it a try, and let him know what features you use File Manager for that are missing or not working in a way that makes sense to you. But, honestly, I think the UI for it is already better than File Manager (which shouldn't be too surprising, since File Manager is a 15+ year old Java applet), though it definitely doesn't have all the functionality of File Manager, yet.

**Comment by swelljoe** [comment] 2015-05-09 02:48
Oh, I should also recommend you not grant access to the module to untrusted users until it's had a bit more time and attention. Given that Webmin runs as root, and Filemin has pretty much arbitrary access to everything...even though it *does* have some security checks built in, I would want to see a serious audit before letting just anybody use it. (Also, possibly bugs that could destroy data unexpectedly.)

**Comment by LeeLorenzSr** [comment] 2015-05-09 03:07
Very cool, but as much as I've learned about Linux, I must be missing something, because I downloaded the filemin-0.9.wbm.gz file to my server, and tried to install the menu, but it's saying it doesn't recognize the package as a valid TAR file. It extracted fine to a wbm file, but the install didn't like that, either.

I usually figure this stuff out fairly quickly... webmin didn't like it when I updated to the Authentic theme just now, because I was missing perl modules, but I was able to install LWP and get it rolling just fine, so I don't think I'm being dense :)

**Comment by swelljoe** [comment] 2015-05-09 03:25
The latest version of Authentic (from https://raw.githubusercontent.com/qooob/authentic-theme/master/.build/authentic-theme-latest.wbt.gz ) does not require LWP or any other external dependencies. I believe you'll need that one to effectively use Filemin (and there might actually still be an AJAX loading bug).

I had similar troubles getting the Filemin module installed (downloading the Raw file with curl or wget is tricky). The way I finally got it to work was to download the .wbm.gz to my desktop and then use the "Upload" option in the Webmin Install Module form.

**Comment by LeeLorenzSr** [comment] 2015-05-09 04:07
OK, I now see I was not getting the proper binary from github. It looks great so far, though it only gives me access to my home folder.

**Comment by swelljoe** [comment] 2015-05-09 05:30
Yes, that's apparently the current design. If you're logged in as root or an administrative user (I guess) you should have access to everything. Regular users get locked into home, it seems, by design. Which is probably a reasonable design option for early versions, given how dangerous this has the potential to be.

**Comment by l-arnold** [comment] 2015-06-12 01:03
Check this.  Might be able to have it available in community packages;
Alexandr Bezenkov (real gecko)  https://github.com/Real-Gecko/filemin.git

I don't know it but I cannot take trying to keep browsers, java etc happy on simple installs.  I usually don't put SSL on Admin ports and all works except File Manager which I find otherwise incredibly useful.

**Comment by swelljoe** [comment] 2015-06-13 02:42
Look in the /install directory in the github for filemin. There are already .wbm and .deb packages for Filemin. You can download either using the raw download option, and use the Webmin Modules module to install it.

We do plan to integrate it into Webmin core going forward, but it's not ready for that yet; it needs some security auditing, accessibility testing, and a few other bits of due diligence before we hand it off to a million users.

**Comment by LeeLorenzSr** [comment] 2015-08-29 21:26
What's the latest on this? The deadline is looming near for Java to be banished from most, if not all, web browsers.

**Comment by jcameron** [comment] 2015-08-29 22:12
The latest development version of Webmin, available from http://www.webmin.com/devel.html , already includes the new file manager.

**Comment by swelljoe** [comment] 2016-05-30 06:43
New File Manager is very solid now, with most of the features people have asked for, so I'm gonna close this issue. Any future requests can be filed as new tickets. The file manager in Webmin has kinda been forked from the Filemin file manager linked earlier. So, if you're using the one shipped with Webmin, you'll want to file tickets here...if you're using Filemin from Real Gecko's repo, you'd want to file requests there.

**Closed by swelljoe** 2016-05-30 06:43 UTC
