### ISSUE TITLE
Unable to login or change password

### ISSUE THREAD

**Issue by tudorminator** [webmin/webmin#1324] opened 2020-11-11 13:22 UTC
**Webmin version**:
- **`1.960`** installed from downloded .deb file
- **`1.96211111032`** installed using `update-from-repo.sh`

**Linux version**:

```sh
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux virtual-srv 4.15.0-122-generic #124-Ubuntu SMP Thu Oct 15 13:02:56 UTC 2020 i686 i686 i686 GNU/Linux
```

The install is not new, I had it running for years and kept updated through the UI. It is a qemu VM running on [Proxmox v. 6.2-15](https://www.proxmox.com/en/) (not sure it matters). Today, after changing my linux user password using `passwd` in a ssh session, logging in using that username was no longer possible. Root login is disabled, there is no other user available to test, although I can create it if necessary.

### Steps to reproduce:
1. Change linux password using `passwd` in a ssh session;
2. Try to login to Webmin version 1.960 using the newly changed password: got _Login failed_ error;
3. Change webmin password using `changepass.pl` in a ssh session; made it a really simple and short password to avoid typing mistakes;
4. Try to login again; got past the login page and onto the page saying _You must select a new password to replace your temporary login._
5. Used the short and simple password as the current password, another similarly simple and short one for the new password;
6. On form submit, devtools console briefly displays a (probably unrelated) error: `Uncaught ReferenceError: $ is not defined at spinner (session_login.cgi:256) at HTMLFormElement.onsubmit (session_login.cgi:28)`;
7. `POST` to `password_change.cgi` responds with `Satus Code: 200 Document follows`, the page displays only the error message **Failed to change password : The current password is incorrect**.

I was completely unable to get past this step no matter what combination of current/new passwords I used, or how many times I rebooted the machine and/or restarted webmin and/or changed password both for the linux and webmin user. There's always the same error. I don't understand how could the **current** password be incorrect since I got past the login screen...

Updating to the development version using `update-from-repo.sh` made absolutely NO difference.

Please let me know what other information you need to debug this issue, I will be more than happy to assist. Thank you.

**Comment by iliarostovtsev** [comment] 2020-11-11 19:10
@jcameron I can confirm this issue happening with new and old themes. 

When config has set to `md5pass=2`, using new `encrypt_sha512` it works just fine. Should we set that to be new default and use SHA512 encryption, as default hashing format instead?

**Comment by iliarostovtsev** [comment] 2020-11-11 19:13
> I was completely unable to get past this step no matter what combination of current/new passwords I used, or how many times I rebooted the machine and/or restarted webmin and/or changed password both for the linux and webmin user.

As a workaround change mentioned above option in `/etc/webmin/config` and restart Webmin with `/etc/webmin/restart` command.

> I don't understand how could the current password be incorrect since I got past the login screen...

Easily. Plain text password must be hashed first and two hashed strings compared (stored and newly supplied). If hashing mechanism is different, then produced strings are also not going to match.

**Comment by iliarostovtsev** [comment] 2020-11-11 19:41
.. or @jcameron perhaps password change tool should consider hashing mechanism set in config?

**Comment by tudorminator** [comment] 2020-11-11 23:41
> Easily. Plain text password must be hashed first and two hashed strings compared (stored and newly supplied). If hashing mechanism is different, then produced strings are also not going to match.

It never occurred to me that the login page could use a different hashing algorithm than the change password page... maybe because it shouldn't happen? 😉

>As a workaround change mentioned above option in /etc/webmin/config and restart Webmin with /etc/webmin/restart command.

I can confirm:  changing `md5pass=1` to `md5pass=2` in `/etc/webmin/config` and restarting webmin **solves the issue**. I successfully changed the password and subsequently logged in using the changed password.

Thank you for your help. And thank you for your work on this great project!

**Comment by jcameron** [comment] 2020-11-12 05:07
Regardless of how the password is hashed by changepass.pl , Webmin should still accept it at login time. This is because the code in miniserv.pl that does password comparison with the hash looks at the hash format to determine the correct hashing type : https://github.com/webmin/webmin/blob/master/miniserv.pl#L5284

**Comment by tudorminator** [comment] 2020-11-12 05:34
> Regardless of how the password is hashed by changepass.pl , Webmin should still accept it at login time.

I hope i got it right, but login does not seem to be the issue here; the problem is that the change password page compares the **current** password's hash to the wrong hash and then refuses to change it, so the user is stuck in a loop between login and mandatory change of temporary password.

**Comment by iliarostovtsev** [comment] 2020-11-12 14:44
@jcameron Jamie, it looks as a bug to me. Have a look https://github.com/webmin/webmin/pull/1326.

**Comment by iliarostovtsev** [comment] 2020-11-12 15:01
@jcameron The source of the problem is [this](https://github.com/webmin/webmin/blob/master/changepass.pl#L43-L44).

If **Webmin Configuration > Authentication > Webmin password hashing format** is set to _crypt_ - all is fine, because this is the format that _changepass.pl_ utility uses. However, this utility disregards MD5 and SHA512. It means that if option `md5pass` set to `1` (_MD5_) or `2` (SHA512) it wouldn't work, as the password that is created with this tool is always in _crypt_ format.

**Comment by iliarostovtsev** [comment] 2020-11-12 15:26
@jcameron have a look at [this patch](https://github.com/webmin/webmin/pull/1326/commits/9711e9c2a982cc587978d40b74d028f974495818) under the same PR.

**Comment by iliarostovtsev** [comment] 2020-11-12 20:12
Added few UI improvements and theme fixes for password change page.
https://github.com/webmin/webmin/commit/796028884c7d1af75d8441371215e571ccec09a2

**Comment by jcameron** [comment] 2020-11-13 06:15
Ok I see the cause of this - the way password_change.cgi checks the existing password is wrong. I'll check in a fix..

**Comment by iliarostovtsev** [comment] 2020-11-13 08:59
@tudorminator Thanks for reporting it. It will be fixed in Webmin 1.963+.

**Closed by iliarostovtsev** 2020-11-13 08:59 UTC

**Comment by tudorminator** [comment] 2020-12-01 17:48
> @tudorminator Thanks for reporting it. It will be fixed in Webmin 1.963+.

Thank **YOU** for your great work. Much appreciated!

**Comment by gcampedelli** [comment] 2021-01-21 15:02
Im unable to login

**Comment by iliarostovtsev** [comment] 2021-01-21 15:05
What error do you see?

**Comment by gcampedelli** [comment] 2021-01-21 15:59
I guess password is wrong. But unable to change password since ./acl/md5-lib.pl is not found
So I manually changed the path and it worked.
