### ISSUE TITLE
Webmin language on the left - not able to change submenu language

### ISSUE THREAD

**Issue by maehschaf** [webmin/webmin#934] opened 2018-07-06 10:44 UTC
Hello,

I am running Webmin 1.881 on OpenSUSE Leap 15. When I log in as root and change the Default language to German, the menu items change i.E. from "Network" to "Netzwerk".

But in the second row everything stays the same, i.E. System/Bootup and Shutdown, which is not the German translation.

Can You please give me an advice?

Regards,
Martin

PS: found [this](https://www.virtualmin.com/node/18999), but do not know how to do it.

PPS: found out, that changing language to "de" changes the module names, changing language to de.UTF-8 does not...

**Comment by jcameron** [comment] 2018-07-06 17:19
Can you attach a screenshot of these missing translations?

**Comment by maehschaf** [comment] 2018-07-06 21:12
![grafik](https://user-images.githubusercontent.com/16573931/42400492-1240dfd6-8172-11e8-9125-68348c15fb49.png)

**Comment by jcameron** [comment] 2018-07-07 18:55
Ok, I see the cause of this - it will be fixed in the next Webmin release.

**Closed by jcameron** 2018-07-07 18:55 UTC
