### ISSUE TITLE
Command Shell Entering Issue

### ISSUE THREAD

**Issue by alexnya** [webmin/webmin#943] opened 2018-07-18 19:09 UTC
Hi,

I'm having an issue using the command shell where basically I can't run commands that require input. It just completely skips over the parts where I have to enter input. For example, I'm trying to set up an SSL certificate for one of my sites but it asks for me to agree (A) or cancel (C). It won't let me choose either and just skips over it and presents an error even though I only pressed enter once. I hope this makes sense.

Thank you, 
Alex Nyamweya

**Comment by alexnya** [comment] 2018-07-18 20:01
Also I can't right click to edit a file for some reason.

**Comment by swelljoe** [comment] 2018-07-19 02:21
It's not an interactive shell. So, behaving as expected.

There need to be significant backend changes to make it work interactively. It's on the radar (and there's a couple of other tickets about it), but it's not a small project and isn't a bug...it's just the way things are right now.

To "fix" it, we need WebSockets support in Webmin's web server, plus a JavaScript terminal emulator on the client side, plus a few other bits and pieces.

**Comment by alexnya** [comment] 2018-07-19 02:34
What about my issue presented in my second post? I can't upload and edit files like I used to. How can I  get an SSL certificate without using the shell?

**Comment by swelljoe** [comment] 2018-07-19 03:00
The second issue sounds like a theme issue (Authentic has a lot of extra code with regard to the File Manager and how it works). Open a new ticket over there on Ilia's Authentic repo, and also include your browser and OS details. I'd recommend checking in another browser first, so you can provide good information to Ilia about how to reproduce it and whether it is browser-specific (also note that Authentic no longer supports Internet Explorer...you'll need to use the old theme if you have to use IE; all modern browsers should work, though, including Edge).

As for your SSL question, are you using Virtualmin? It has SSL certificate management and generation, including Let's Encrypt support, built-in. It's in the Server Configuration menu for each domain). If not, I guess you'll need to login via an interactive terminal (ssh, or the AJAXTerm Webmin module, if you need it to be in Webmin), or add flags to the command to make it work non-interactively.

**Comment by swelljoe** [comment] 2018-07-19 03:01
I'm gonna close this, as it's not a bug and we have a couple of other tickets about the original issue.

**Closed by swelljoe** 2018-07-19 03:01 UTC
