### ISSUE TITLE
Submit buttons on Cluster Software

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#784] opened 2018-01-25 10:12 UTC
Jamie, we have another place where buttons don't submit the forms.
https://github.com/qooob/authentic-theme/issues/992

It is in `Cluster/Cluster Software Packages`.

**Comment by qooob** [comment] 2018-01-25 11:14
+ the same happens for me in Software Packages/Package search/Edit Package.

List Files and uninstall buttons also don't work (tested on Debian but I think the same will be on other distros).

**Comment by jcameron** [comment] 2018-01-26 04:23
Fix for the cluster software packages module is checked in, the regular software packages module was already fixed in another bug.

**Closed by jcameron** 2018-01-26 04:23 UTC

**Comment by Chaots** [comment] 2018-02-06 11:50
How may i get this updated patch? i have some 40 webmin / virtualmin servers that do not seem to have gotten an update for this cluster functionality.

It seems the modules do work in general. the first "option / form" in each of the cluster modules seem to fail. as if the form was not created properly. the second option on each of the cluster modules seem to work.

cluster --> cluster webmin servers --> option add server first and only option does not work. i cant add more servers / the first server in a new cluster.

in an existing cluster i can not add servers from a group, defined in webmin -> webmin servers index. although the cluster -> cluster webmin servers -> options "upgrade webmin" and "update modules" on already clustered machines, does work just fine.

cluster shell commands seems to work just fine

Cluster -> cluster software packages. adding servers to ( an existing ) group does not work, neither does compare servers. both once again seem to be part of the first "option form" above the "</hr>" though search for a packages, or refreshing package lists words again.

I suspect that the issue is not really in the back end code, though more in the building of the "html forms"

Steven

**Comment by jcameron** [comment] 2018-02-07 00:20
Yes, this is an HTML bug.  The specific fixes are : 

https://github.com/webmin/webmin/commit/d06e48f175f9b3e58c16ccdb5253dcb975ed9b39
and
https://github.com/webmin/webmin/commit/57a4dfc3106d556e134f894d4ea1ded6c7fb4e91#diff-f9fa10ba956cacf91d7878861139efb9

**Comment by qooob** [comment] 2018-02-21 13:11
Jamie, there are few more to fix:

> Can not add servers to (When pressing on the button "Add server" nothing happens)
 Cluster Webmin Servers
  Cluster Usermin Servers
  Cluster Software Packages

https://github.com/qooob/authentic-theme/issues/1021

**Comment by qooob** [comment] 2018-03-06 07:26
Thank you for the fix. I checked it again but:

* **Cluster Usermin Servers**

Also at **Cluster Webmin Servers**

   _Add User, Add Group_ and  _Synchronize_  buttons don't work.

At **Cluster Software Packages** the button *Compare Servers* don't work.

**Comment by Chaots** [comment] 2018-03-08 18:34
I can confirm these features do not work as of yet, is there anything i can do in trying to get these features fixed?

**Comment by jcameron** [comment] 2018-03-09 23:26
I just checked in a couple more fixes for those forms - see the commits on this bug report.

**Comment by qooob** [comment] 2018-03-10 16:11
Jamie, thanks. I have went through and there are more parts to fix. Please do. Simply look at the screenshots. Please write some thing here, so I'd know when it's done, to do more checks.

![screenshot from 2018-03-10 19-07-28](https://user-images.githubusercontent.com/4426533/37244236-d298c5ca-2496-11e8-89e8-121d20b94984.png)
![screenshot from 2018-03-10 19-05-09](https://user-images.githubusercontent.com/4426533/37244237-d2c15d78-2496-11e8-97e6-b8233438aef4.png)
![screenshot from 2018-03-10 19-01-42](https://user-images.githubusercontent.com/4426533/37244238-d2e50d2c-2496-11e8-915b-0ad02aebf424.png)

**Comment by qooob** [comment] 2018-03-10 16:45
..and one more:

![screenshot from 2018-03-10 19-42-33](https://user-images.githubusercontent.com/4426533/37244531-838aafe8-249b-11e8-82f8-4afb27895969.png)

**Comment by jcameron** [comment] 2018-03-11 19:05
Ok, I've committed fixes for these.
