### ISSUE TITLE
2FA does not load QR code

### ISSUE THREAD

**Issue by Lawkss** [webmin/webmin#2115] opened 2024-04-05 20:07 UTC
When enabling 2FA it displays the text key but not the QR code. 

This is the error: 

net::ERR_BLOCKED_BY_ORB

It happens in Edge and Chrome, I don't think it is a browser issue on my end.

**Comment by chris001** [comment] 2024-04-05 20:48
ORB is Opaque Request Blocked.  It's a cross-origin error.
https://groups.google.com/a/chromium.org/g/blink-dev/c/ScjhKz3Z6U4?pli=1

**Comment by jcameron** [comment] 2024-04-06 00:58
Which 2FA provider were you trying to use?

**Comment by jcameron** [comment] 2024-04-07 00:55
Looks like there's some discussion of the issue with the Google QR code API here : https://www.googlecloudcommunity.com/gc/AppSheet-Q-A/QR-Code-Generator-not-working/m-p/696385

**Comment by jcameron** [comment] 2024-04-07 01:13
Ok I think I see the cause of this - it's fixed in this commit https://github.com/webmin/webmin/commit/64211e46cbefbda984bf3bf4914337e6f3fa6dde and will be included in the next Webmin release.

**Closed by jcameron** 2024-04-07 01:13 UTC

**Comment by chris001** [comment] 2024-04-07 04:43
There's been talk of the QR code API having been deprecated.
https://groups.google.com/g/google-visualization-api/c/Pzzya6ed14g

**Comment by swelljoe** [comment] 2024-04-07 06:50
Should probably build the QR code locally instead of via an API, especially if Google is turning theirs off. There's a `qrencode` package in probably every major Linux distro, which can produce a PNG. There's Perl bindings for libqrencode, but I don't think that'd be easier to integrate, since it's an XS module and not widely available in distro repos.

There's probably some pure Perl or Python implementation out there, too, that could be bundled. I only found console versions, though, in a quick search, which wouldn't be as useful.

**Comment by iliajie** [comment] 2024-04-07 15:13
I have run tests with all the latest changes, and the QR code is displayed properly again.

**Comment by chris001** [comment] 2024-04-07 20:03
From: https://groups.google.com/g/google-visualization-api/c/Pzzya6ed14g/m/5NGXkwwjBwAJ

> Jon Orwant
> Jan 10, 2024, 1:54:57 PM
> to Google Visualization API
> Yes, you should change to another solution; some have been mentioned on this group and others. I'm turning the service off, and then back on, to alert users that they're relying on a moribund service without pulling the plug abruptly.
>
> Jon

**Comment by jcameron** [comment] 2024-04-07 21:52
> Should probably build the QR code locally instead of via an API, especially if Google is turning theirs off. 

Yeah, that seems like the right call. This module might work : https://metacpan.org/pod/Image::PNG::QRCode

**Comment by swelljoe** [comment] 2024-04-07 22:18
That one isn't pure Perl (has some C code that has to be built), and it's not in our supported distro repos.

**Comment by swelljoe** [comment] 2024-04-07 22:18
https://metacpan.org/release/BKB/Image-PNG-QRCode-0.10/source

**Comment by jcameron** [comment] 2024-04-07 22:33
Hmmm ... it doesn't look like there are any pure perl modules unfortunately :-(

There's https://metacpan.org/pod/Imager::QRCode but it also need a library.

**Comment by swelljoe** [comment] 2024-04-07 23:07
It'd be fine if those modules were in the OS repos, but only the command line tool `qrencode` is widely available.

**Comment by jcameron** [comment] 2024-04-07 23:15
Ok I've checked in some code to use `qrencode` or `Image::PNG::QRCode` if either are installed. I can also add `qrencode` as a dependency of the Webmin packages...

**Comment by swelljoe** [comment] 2024-04-07 23:17
Probably ought to be a soft dependency.

**Comment by Lawkss** [comment] 2024-04-08 00:48
Thank you very much for your work! Yum'd qrencode an looking forward to try it again in the upcoming versions.

**Comment by chris001** [comment] 2024-04-08 00:56
What about this one, it seems to be perl only: https://github.com/Tekki/svg-barcode-qrcode
