### ISSUE TITLE
Can we have KEA DHCP buil in to the webmin?

### ISSUE THREAD

**Issue by doremo2021** [webmin/webmin#2120] opened 2024-04-11 02:19 UTC
I am reaching out to propose the integration of KEA DHCP server management capabilities into the Webmin control panel. As you may know, KEA is a modern, open-source DHCP server developed by the Internet Systems Consortium, offering significant improvements over the traditional ISC DHCP server in terms of performance, scalability, and extensibility.

**Comment by swelljoe** [comment] 2024-04-11 02:56
Are you offering to either perform that development yourself or sponsor that development? If not, I'm closing this as a duplicate of this ticket: https://github.com/webmin/webmin/issues/2118

**Closed by swelljoe** 2024-04-11 02:56 UTC
