### ISSUE TITLE
Search: Fails on Fedora 27

### ISSUE THREAD

**Issue by rostovtsev** [webmin/webmin#800] opened 2018-02-01 19:56 UTC
Jamie, hi.

I checkd the code and can't understand why this is happening. Failed `cgi_page_title` has to be embedded with `webmin-search-lib.pl`.

I have this error:

![screenshot from 2018-02-01 22-43-18](https://user-images.githubusercontent.com/4426533/35699855-575b5ca8-07a2-11e8-8371-30051fd6ad77.png)

**Comment by jcameron** [comment] 2018-02-02 00:57
Can you add the line `error_stack=1` to `/etc/webmin/config` so that the full error trace is displayed?

**Comment by qooob** [comment] 2018-02-02 11:56
Jamie, I did it. There is not much trace in `miniserv.error` file.

All it has is:

```
[02/Feb/2018:14:54:17 +0300] [1.2.3.4] /webmin_search.cgi : Perl execution failed : Undefined subroutine &main::cgi_page_title called at /usr/libexec/webmin/webmin_search.cgi line 55.
```

**Comment by qooob** [comment] 2018-02-02 11:57
The same error appears in Gray Theme, just in case.

**Comment by jcameron** [comment] 2018-02-03 00:55
What word did you search for exactly?

**Comment by jcameron** [comment] 2018-02-03 01:05
I did a test search for "telnet" and it worked OK

**Comment by qooob** [comment] 2018-02-03 06:06
I tried different ones. As you can see from screenshot it was `upl`.

**Comment by gnadelwartz** [comment] 2018-02-03 09:41
did you try on a fresh installation of 1.873 or had you done update-from-repo before?

btw: i have the same issue .

**Comment by qooob** [comment] 2018-02-03 09:42
No, this is from the package. (Yum)

**Comment by gnadelwartz** [comment] 2018-02-03 10:08
my issue vanished after fresh installation of 1.873 dev tarball and latest stable of authentic:
![image](https://user-images.githubusercontent.com/4593242/35766086-5a35255a-08d1-11e8-9b41-af9ffa20f4d7.png)

its also working after using LATEST update-from-repo, do not use the one from 1.873, its broken
![image](https://user-images.githubusercontent.com/4593242/35766133-468ec898-08d2-11e8-81a3-29f631db6d58.png)
![image](https://user-images.githubusercontent.com/4593242/35766137-5765619a-08d2-11e8-966c-be9cebb871a6.png)

**Comment by qooob** [comment] 2018-02-03 10:09
Did you also have this issue?

**Comment by qooob** [comment] 2018-02-03 10:53
The problem is, that this issue only happened on Fedora 27, while CentOS and Debian were just fine.

**Comment by gnadelwartz** [comment] 2018-02-03 12:33
yes I had this also on synology, may be it happend while  developing or update-script was broken.
Now its gone ...

**Comment by qooob** [comment] 2018-02-03 12:36
No, it's not.

It's in the distro package.

**Comment by gnadelwartz** [comment] 2018-02-03 12:43
'it's gone' was for my problem :-)

**Comment by gnadelwartz** [comment] 2018-02-03 12:45
yum is rpm packages?

**Comment by qooob** [comment] 2018-03-24 17:51
The same error is present.

**Comment by qooob** [comment] 2018-04-01 11:36
Jamie, it's easy to reproduce by installing Fedora.

It still returns an error:

```Perl
Error - Perl execution failed
Undefined subroutine &main::cgi_page_title called at /usr/libexec/webmin/webmin_search.cgi line 55.
```

**Comment by jcameron** [comment] 2018-04-01 22:17
Which perl version is Fedora 27 running?

**Comment by qooob** [comment] 2018-04-01 22:19
5.26.1

**Comment by reers** [comment] 2018-07-01 19:45
Hi, same error here on ubuntu 18.04 with perl 5.26.1, fresh install. Any fix?
Thank you.

**Comment by jcameron** [comment] 2018-07-04 23:38
This will be fixed in the next webmin release - the specific patch can be seen here : https://github.com/webmin/webmin/commit/dbe8bfb7d6dcaf45374c58c1e7ac9b194fcfd167

**Closed by jcameron** 2018-07-04 23:38 UTC
