### ISSUE TITLE
Undefined subroutine &firewall6::get_module_acl called at /usr/share/webmin/firewall6/firewall6-lib.pl line 21.

### ISSUE THREAD

**Issue by TheBudda** [webmin/webmin#1596] opened 2022-02-07 06:33 UTC
I got this issue pop up after a fresh install on ubuntu 20.04.3 and installing webmin on my home PC.  Only when I click IP^ Firewall settings cog at the top. So, I checked my dedi server and a Debian VPS. I got the same error on all OVH boxes and my home PC. (please see screenshot) I did google of course and tried one of your fixes but did not do the job

Require firewall6/firewall6-lib.pl failed : Undefined subroutine &firewall6::get_module_acl called at /usr/share/webmin/firewall6/firewall6-lib.pl line 21

![Configuration_Linux_IPv6_Firewall_2022-02-07_06-27](https://user-images.githubusercontent.com/16983376/152735887-bf7a38fa-9e8a-429f-addd-d90a90e39daf.png)
.

My OVH dedicated server is running ubuntu 20.4.3, my home PC is the same. VPS is Debian Linux 10

**Comment by jcameron** [comment] 2022-02-07 19:43
How did you install Webmin on this system? Was it from the Debian package that we provide?

**Comment by TheBudda** [comment] 2022-02-07 19:58
> How did you install Webmin on this system? Was it from the Debian package that we provide?

I installed webmin via your repo [deb https://download.webmin.com/download/repository sarge contrib] 

Has per instruction https://www.webmin.com/deb.html

**Comment by jcameron** [comment] 2022-02-08 06:08
Ok I see the cause of this bug now - it will be fixed in the next Webmin release.

**Closed by jcameron** 2022-02-08 06:08 UTC
