### ISSUE TITLE
Fedora: Change password

### ISSUE THREAD

**Issue by qooob** [webmin/webmin#673] opened 2017-10-27 11:17 UTC
Jamie, hi. Using Fedora and latest Webmin makes list of users doubled.

Have a look:

![screenshot from 2017-10-27 14-14-36](https://user-images.githubusercontent.com/4426533/32101589-77893996-bb21-11e7-88e5-c514ef0c19d4.png)

This happens in all themes.

**Comment by jcameron** [comment] 2017-10-27 23:36
Wow, that's odd ... which Fedora version is this?

**Comment by jcameron** [comment] 2017-10-27 23:36
Also, do those users appear twice in `/etc/passwd` ?

**Comment by swelljoe** [comment] 2017-10-28 08:21
I can't reproduce this on my Fedora 26 system.

**Comment by qooob** [comment] 2017-10-28 08:32
It happens on two different machines and one of them is clean install.

Users and Groups shows everything correctly.

**Comment by qooob** [comment] 2017-10-28 11:23
Definitely not. It's **Fedora Linux 26 Server Edition**. Have a look

```list
[root@debug-fedora ~]# cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
systemd-coredump:x:999:998:systemd Core Dumper:/:/sbin/nologin
systemd-timesync:x:998:997:systemd Time Synchronization:/:/sbin/nologin
systemd-network:x:192:192:systemd Network Management:/:/sbin/nologin
systemd-resolve:x:193:193:systemd Resolver:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
polkitd:x:997:996:User for polkitd:/:/sbin/nologin
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
rpc:x:32:32:Rpcbind Daemon:/var/lib/rpcbind:/sbin/nologin
abrt:x:173:173::/etc/abrt:/sbin/nologin
cockpit-ws:x:996:994:User for cockpit-ws:/:/sbin/nologin
rpcuser:x:29:29:RPC Service User:/var/lib/nfs:/sbin/nologin
chrony:x:995:993::/var/lib/chrony:/sbin/nologin
tcpdump:x:72:72::/:/sbin/nologin
tss:x:59:59:Account used by the trousers package to sandbox the tcsd daemon:/dev/null:/sbin/nologin
apache:x:48:48:Apache:/usr/share/httpd:/sbin/nologin
clamupdate:x:994:992:Clamav database update user:/var/lib/clamav:/sbin/nologin
clamscan:x:993:990:Clamav scanner user:/:/sbin/nologin
nginx:x:992:989:Nginx web server:/var/lib/nginx:/sbin/nologin
mysql:x:27:27:MySQL Server:/var/lib/mysql:/sbin/nologin
grmilter:x:991:988:Greylist-milter user:/var/lib/milter-greylist:/sbin/nologin
opendkim:x:990:987:OpenDKIM Milter:/var/run/opendkim:/sbin/nologin
postgrey:x:989:986:Postfix Greylisting Service:/var/spool/postfix/postgrey:/sbin/nologin
dovecot:x:97:97:Dovecot IMAP server:/usr/libexec/dovecot:/sbin/nologin
dovenull:x:988:985:Dovecot's unauthorized user:/usr/libexec/dovecot:/sbin/nologin
webalizer:x:67:984:Webalizer:/var/www/usage:/sbin/nologin
postfix:x:89:89::/var/spool/postfix:/sbin/nologin
sphinx:x:987:983:Sphinx Search:/usr/lib/tmpfiles.d/lib/sphinx:/bin/bash
saslauth:x:986:76:Saslauthd user:/run/saslauthd:/sbin/nologin
named:x:25:25:Named:/var/named:/sbin/nologin
```

```
[root@debug-fedora ~]# uname -a
Linux debug-fedora 4.13.5-200.fc26.x86_64 #1 SMP Thu Oct 5 16:53:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

```
[root@debug-fedora ~]# lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 26 (Twenty Six)
Release:	26
Codename:	TwentySix
```

**Comment by jcameron** [comment] 2017-10-29 05:49
If you run the `getent passwd` command, does it also list all users twice?

**Comment by qooob** [comment] 2017-10-29 07:27
Yes, they are shown twice. Almost all of them but not all. Users with home equal to `/root` shows only once ALL other shown twice.

For me it seems as Fedora bug 

I think you need to unique output by username.

**Comment by swelljoe** [comment] 2017-10-29 10:01
I'd rather understand why `getent passwd` is returning bogus extra results before changing Webmin; it may be telling the truth as far as the system is concerned. Do you have other sources of user data (e.g. LDAP, or some other user database)?

**Comment by jcameron** [comment] 2017-10-29 15:48
I'll check in a fix to skip duplicate users, since it makes no sense to display them in that module.

**Comment by qooob** [comment] 2017-10-29 15:54
@swelljoe No. It's just clean install.

**Comment by jcameron** [comment] 2017-10-29 15:55
Fix to the fix committed. I agree that this is a Fedora bug of some kind though..

**Comment by chris001** [comment] 2017-10-29 16:16
@iliaross Is it possible you have users coming from LDAP (PAM) and also coming from Unix local users

**Comment by qooob** [comment] 2017-10-29 16:46
@chris001 I don't use LDAP. It's been happening on two different machines.

**Closed** 2017-12-04 12:23 UTC
