### ISSUE TITLE
Webmin restart failed on systemd

### ISSUE THREAD

**Issue by macmon** [webmin/webmin#1228] opened 2020-04-06 13:53 UTC
If Webmin is restarted via _System_ → _Bootup and Shutdown_, the Webmin process is terminated.
If you then try to restart Webmin in the console with `systemctl start webmin.service` Webmin will not start. Only a `systemctl restart webmin.service` starts Webmin again:

```
macmon:~# systemctl status webmin.service 
● webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: active (running) since Mon 2020-04-06 14:28:56 CEST; 34s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 24342 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)
    Tasks: 2 (limit: 4700)
   Memory: 28.6M
   CGroup: /system.slice/webmin.service
           └─24344 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf

Apr 06 14:28:53 macmon systemd[1]: Starting LSB: web-based administration interface for Unix systems...
Apr 06 14:28:53 macmon perl[24343]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Apr 06 14:28:56 macmon webmin[24343]: Webmin starting
Apr 06 14:28:56 macmon systemd[1]: Started LSB: web-based administration interface for Unix systems.
macmon:~# # goto https://192.168.1.17:10000/init/?xnavigation=1 and restart webmin
macmon:~# systemctl status webmin.service 
● webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: active (exited) since Mon 2020-04-06 14:28:56 CEST; 2min 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 24342 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)

Apr 06 14:28:53 macmon systemd[1]: Starting LSB: web-based administration interface for Unix systems...
Apr 06 14:28:53 macmon perl[24343]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Apr 06 14:28:56 macmon webmin[24343]: Webmin starting
Apr 06 14:28:56 macmon systemd[1]: Started LSB: web-based administration interface for Unix systems.
macmon:~# systemctl start webmin.service 
macmon:~# systemctl status webmin.service 
● webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: active (exited) since Mon 2020-04-06 14:28:56 CEST; 2min 20s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 24342 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)

Apr 06 14:28:53 macmon systemd[1]: Starting LSB: web-based administration interface for Unix systems...
Apr 06 14:28:53 macmon perl[24343]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Apr 06 14:28:56 macmon webmin[24343]: Webmin starting
Apr 06 14:28:56 macmon systemd[1]: Started LSB: web-based administration interface for Unix systems.
macmon:~# systemctl restart webmin.service 
macmon:~# systemctl status webmin.service 
● webmin.service - LSB: web-based administration interface for Unix systems
   Loaded: loaded (/etc/init.d/webmin; generated)
   Active: active (running) since Mon 2020-04-06 14:31:24 CEST; 1s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 25799 ExecStart=/etc/init.d/webmin start (code=exited, status=0/SUCCESS)
    Tasks: 4 (limit: 4700)
   Memory: 50.2M
   CGroup: /system.slice/webmin.service
           ├─25801 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf
           ├─25803 /usr/share/webmin/webmincron/webmincron.pl
           ├─25822 sh -c (vmstat 1 2 2>/dev/null)
           └─25823 vmstat 1 2

Apr 06 14:31:22 macmon systemd[1]: Starting LSB: web-based administration interface for Unix systems...
Apr 06 14:31:22 macmon perl[25800]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Apr 06 14:31:24 macmon webmin[25800]: Webmin starting
Apr 06 14:31:24 macmon systemd[1]: Started LSB: web-based administration interface for Unix systems.
macmon:~#
```

Why is Webmin not installed Systemd script eg. `/lib/systemd/system/webmin.service`?

The system is a Debian 10 (Buster) Linux.

**Comment by jcameron** [comment] 2020-04-12 02:45
Looks like there's a bug in which webmin can kill itself before completing the process of running the systemd action. This will be fixed in the next release.

**Closed by jcameron** 2020-04-12 02:45 UTC

**Comment by Jibun-no-Kage** [comment] 2022-10-05 22:59
Was this issue fixed?  I just got it today, install WebMin on Pi OS 11 (Debian 11 ARM variant).  WebMin starts then fails with a timeout error?

A start job for unit webmin.service has begun execution.
░░
░░ The job identifier is 2467.
Oct 05 22:53:07 template.dd.org perl[2576]: pam_unix(webmin:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=  user=root
Oct 05 22:53:09 template.dd.org webmin[2576]: Webmin starting
Oct 05 22:53:15 template.dd.org systemd[1]: webmin.service: start operation timed out. Terminating.
Oct 05 22:53:15 template.dd systemd[1]: webmin.service: Failed with result 'timeout'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit webmin.service has entered the 'failed' state with result 'timeout'.
Oct 05 22:53:15 template.dd.org systemd[1]: Failed to start Webmin server daemon.
░░ Subject: A start job for unit webmin.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit webmin.service has finished with a failure.
░░
░░ The job identifier is 2467 and the job result is failed.
Oct 05 22:53:15 template.dd.org systemd[1]: webmin.service: Consumed 13.059s CPU time.

Any help appreciated.

**Comment by chris001** [comment] 2022-10-05 23:26
Same, uploaded new self signed cert and key, also clicked to publish to all services, at some point when it tried to restart itself to pick up the new ones, it hung, a red popup came in browser saying unable to connect.  Had to go command line and restart it.

**Comment by jcameron** [comment] 2022-10-06 00:25
This seems different from the original bug. 

@chris001 or @Jibun-no-Kage does anything useful get logged to `/var/webmin/miniserv.error` ?

**Comment by chris001** [comment] 2022-10-06 03:00
No, however, errors are logging in `journalctl -u webmin`
[journalctl.u.webmin.log.txt](https://github.com/webmin/webmin/files/9720797/journalctl.u.webmin.log.txt)

**Comment by chris001** [comment] 2022-10-06 07:29
One clue is that as the (virtual) machine was starting up CPU load average was up around `5.2`.  RAM was `1GB` and there was 1 CPU.  Maybe it was failing because not enough resources until all the other processes finished using the CPU and RAM to start up?  After startup all completed, which takes about 3-4 minutes!, there's about 30% free RAM.

**Comment by iliajie** [comment] 2022-10-06 09:03
@macmon This `systemd` error could happen if Webmin was started somehow else.

What is the output of the following commands:

```
cat /etc/webmin/start
```

and 

```
ps aux | grep miniserv
```

**Comment by chris001** [comment] 2022-10-06 15:38
```
$ cat /etc/webmin/start
#!/bin/sh
/usr/bin/systemctl start webmin
```

```
$ ps aux | grep miniserv
root         922  0.0  0.3  36648  3700 ?        Ss   15:29   0:00 /usr/bin/perl /usr/share/usermin/miniserv.pl /etc/usermin/miniserv.conf
root        2551  0.0  0.8  98012  8016 ?        Ss   15:32   0:00 /usr/bin/perl /usr/share/webmin/miniserv.pl /etc/webmin/miniserv.conf
```

**Comment by Jibun-no-Kage** [comment] 2022-10-06 16:13
I figured out part of my original issue, it was a resource limit.  Once I ran WebMin alone, it worked, so failure to start is resolved in my case.  I still get the PAM auth error, but as I understand it was once a known issue, believe to be addressed?  So not sure the PAM auth issue is a regression of the original issue, or a new variant.

**Comment by jcameron** [comment] 2022-10-07 06:16
The PAM message can be ignored - it's just Webmin checking if PAM is available for password validation.
